In [175]:
import numpy as np
import sympy as sm
import scipy.spatial.transform as transform
np.set_printoptions(suppress=True)
sm.init_printing()

In [78]:
# symbols
# AX = ZB
symTemplates = ['a', 'x', 'z', 'b']
allSymbols = []

# Creating 12 symbols for each matrix
for template in symTemplates:
    allSymbols.append([sm.Symbol(template + str(i)) for i in range(3 * 4)])

display('ALL SYMBOLS:')
for symbols in allSymbols:
    display(symbols)

# Creating matrices from symbols
A = sm.Matrix([allSymbols[0][:4], allSymbols[0][4:8], allSymbols[0][8:12], [0, 0, 0, 1]])
X = sm.Matrix([allSymbols[1][:4], allSymbols[1][4:8], allSymbols[1][8:12], [0, 0, 0, 1]])
Z = sm.Matrix([allSymbols[2][:4], allSymbols[2][4:8], allSymbols[2][8:12], [0, 0, 0, 1]])
B = sm.Matrix([allSymbols[3][:4], allSymbols[3][4:8], allSymbols[3][8:12], [0, 0, 0, 1]])

display('MATRICES:', 'A:', A, 'X:', X, 'Z:', Z, 'B:', B)

equation = A * X - Z * B
display('EQUATION:', equation)


'ALL SYMBOLS:'

'MATRICES:'

'A:'

⎡a₀  a₁  a₂   a₃ ⎤
⎢                ⎥
⎢a₄  a₅  a₆   a₇ ⎥
⎢                ⎥
⎢a₈  a₉  a₁₀  a₁₁⎥
⎢                ⎥
⎣0   0    0    1 ⎦

'X:'

⎡x₀  x₁  x₂   x₃ ⎤
⎢                ⎥
⎢x₄  x₅  x₆   x₇ ⎥
⎢                ⎥
⎢x₈  x₉  x₁₀  x₁₁⎥
⎢                ⎥
⎣0   0    0    1 ⎦

'Z:'

⎡z₀  z₁  z₂   z₃ ⎤
⎢                ⎥
⎢z₄  z₅  z₆   z₇ ⎥
⎢                ⎥
⎢z₈  z₉  z₁₀  z₁₁⎥
⎢                ⎥
⎣0   0    0    1 ⎦

'B:'

⎡b₀  b₁  b₂   b₃ ⎤
⎢                ⎥
⎢b₄  b₅  b₆   b₇ ⎥
⎢                ⎥
⎢b₈  b₉  b₁₀  b₁₁⎥
⎢                ⎥
⎣0   0    0    1 ⎦

'EQUATION:'

⎡ a₀⋅x₀ + a₁⋅x₄ + a₂⋅x₈ - b₀⋅z₀ - b₄⋅z₁ - b₈⋅z₂    a₀⋅x₁ + a₁⋅x₅ + a₂⋅x₉ - b₁⋅
⎢                                                                             
⎢ a₄⋅x₀ + a₅⋅x₄ + a₆⋅x₈ - b₀⋅z₄ - b₄⋅z₅ - b₈⋅z₆    a₄⋅x₁ + a₅⋅x₅ + a₆⋅x₉ - b₁⋅
⎢                                                                             
⎢a₁₀⋅x₈ + a₈⋅x₀ + a₉⋅x₄ - b₀⋅z₈ - b₄⋅z₉ - b₈⋅z₁₀  a₁₀⋅x₉ + a₈⋅x₁ + a₉⋅x₅ - b₁⋅
⎢                                                                             
⎣                       0                                                0    

z₀ - b₅⋅z₁ - b₉⋅z₂    a₀⋅x₂ + a₁⋅x₆ + a₂⋅x₁₀ - b₁₀⋅z₂ - b₂⋅z₀ - b₆⋅z₁     a₀⋅x
                                                                              
z₄ - b₅⋅z₅ - b₉⋅z₆    a₄⋅x₂ + a₅⋅x₆ + a₆⋅x₁₀ - b₁₀⋅z₆ - b₂⋅z₄ - b₆⋅z₅     a₄⋅x
                                                                              
z₈ - b₅⋅z₉ - b₉⋅z₁₀  a₁₀⋅x₁₀ + a₈⋅x₂ + a₉⋅x₆ - b₁₀⋅z₁₀ - b₂⋅z₈ - b₆⋅z₉  a₁₀⋅x₁
                                                   

In [79]:
# Creating linear matrix equations
lA, lb = sm.linear_eq_to_matrix(equation, [x for x in allSymbols[1]] + [z for z in allSymbols[2]])

display('Linear Equation:', 'A:', lA, 'b:', lb)

'Linear Equation:'

'A:'

⎡a₀  0   0   0   a₁  0   0   0   a₂    0    0    0   -b₀  -b₄  -b₈   0    0   
⎢                                                                             
⎢0   a₀  0   0   0   a₁  0   0    0   a₂    0    0   -b₁  -b₅  -b₉   0    0   
⎢                                                                             
⎢0   0   a₀  0   0   0   a₁  0    0    0   a₂    0   -b₂  -b₆  -b₁₀  0    0   
⎢                                                                             
⎢0   0   0   a₀  0   0   0   a₁   0    0    0   a₂   -b₃  -b₇  -b₁₁  -1   0   
⎢                                                                             
⎢a₄  0   0   0   a₅  0   0   0   a₆    0    0    0    0    0    0    0   -b₀  
⎢                                                                             
⎢0   a₄  0   0   0   a₅  0   0    0   a₆    0    0    0    0    0    0   -b₁  
⎢                                                                             
⎢0   0   a₄  0   0   0   a₅  0    0    0   a₆    0  

'b:'

⎡ 0  ⎤
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢-a₃ ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢-a₇ ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢-a₁₁⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎣ 0  ⎦

In [119]:
mlA = sm.Matrix(lA[:-4, :])
mlb = sm.Matrix(lb[:-4])
display('Minimal Linear Equation: ', 'A:', mlA, 'Rank A:', mlA.rank(), 'b:', mlb)

'Minimal Linear Equation: '

'A:'

⎡a₀  0   0   0   a₁  0   0   0   a₂    0    0    0   -b₀  -b₄  -b₈   0    0   
⎢                                                                             
⎢0   a₀  0   0   0   a₁  0   0    0   a₂    0    0   -b₁  -b₅  -b₉   0    0   
⎢                                                                             
⎢0   0   a₀  0   0   0   a₁  0    0    0   a₂    0   -b₂  -b₆  -b₁₀  0    0   
⎢                                                                             
⎢0   0   0   a₀  0   0   0   a₁   0    0    0   a₂   -b₃  -b₇  -b₁₁  -1   0   
⎢                                                                             
⎢a₄  0   0   0   a₅  0   0   0   a₆    0    0    0    0    0    0    0   -b₀  
⎢                                                                             
⎢0   a₄  0   0   0   a₅  0   0    0   a₆    0    0    0    0    0    0   -b₁  
⎢                                                                             
⎢0   0   a₄  0   0   0   a₅  0    0    0   a₆    0  

'Rank A:'

'b:'

⎡ 0  ⎤
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢-a₃ ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢-a₇ ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎣-a₁₁⎦

In [120]:
lhs = sm.kronecker_product(A[:3, :3], sm.eye(4)).row_join(sm.kronecker_product(-sm.eye(3), B.T))
rhs = sm.kronecker_product(A[:3, -1], -sm.Matrix([0, 0, 0, 1]))

display(lhs)
display(rhs)


⎡a₀  0   0   0   a₁  0   0   0   a₂    0    0    0   -b₀  -b₄  -b₈   0    0   
⎢                                                                             
⎢0   a₀  0   0   0   a₁  0   0    0   a₂    0    0   -b₁  -b₅  -b₉   0    0   
⎢                                                                             
⎢0   0   a₀  0   0   0   a₁  0    0    0   a₂    0   -b₂  -b₆  -b₁₀  0    0   
⎢                                                                             
⎢0   0   0   a₀  0   0   0   a₁   0    0    0   a₂   -b₃  -b₇  -b₁₁  -1   0   
⎢                                                                             
⎢a₄  0   0   0   a₅  0   0   0   a₆    0    0    0    0    0    0    0   -b₀  
⎢                                                                             
⎢0   a₄  0   0   0   a₅  0   0    0   a₆    0    0    0    0    0    0   -b₁  
⎢                                                                             
⎢0   0   a₄  0   0   0   a₅  0    0    0   a₆    0  

⎡ 0  ⎤
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢-a₃ ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢-a₇ ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎢ 0  ⎥
⎢    ⎥
⎣-a₁₁⎦

In [122]:
mlb == rhs

True

In [210]:
# Creating dummy dataset
gtAs = []
gtBs = []
gtX = np.eye(4, dtype=float)
gtX[:3, -1] = [1, 2, 3]

gtZ = np.eye(4, dtype=float)
gtZ[:3, -1] = [3, 3, 10]
gtZ[:3, 2] *= -1   # z-Looking down
gtZ[:3, 1] *= -1   # Looking down

numsamples = 10

for i in range(numsamples):
    r = 2 * (np.random.rand(3) - 0.5) * 2 * np.pi
    r /= np.linalg.norm(r)
    t = 2 * (np.random.rand(3) - 0.5) * 5
    
    T = np.eye(4)
    T[:3, :3] = transform.Rotation.from_rotvec(r).as_matrix()
    T[:3, -1] = t
    
    gtAs.append(T.copy())
    
    attachedObjectInStatic = np.dot(np.dot(np.linalg.inv(gtZ), T.copy()), gtX)
    attachedObjectInStatic[:3, -1] += 2.0 * (np.random.rand(3) - 0.5) * 0.01
    gtBs.append(attachedObjectInStatic)
    
    print(T, attachedObjectInStatic)


[[ 0.69113022  0.56454613 -0.45125014  3.24272297]
 [-0.20661948  0.75264941  0.62516178  3.25505801]
 [ 0.69256581 -0.33883113  0.63682498 -3.33834208]
 [ 0.          0.          0.          1.        ]] [[ 0.69113022  0.56454613 -0.45125014  0.70829547]
 [ 0.20661948 -0.75264941 -0.62516178 -3.43365278]
 [-0.69256581  0.33883113 -0.63682498 11.40727838]
 [ 0.          0.          0.          1.        ]]
[[ 0.69806346  0.32132623 -0.63988817 -1.50092218]
 [-0.63314047  0.69437718 -0.34201386 -3.50062775]
 [ 0.33442572  0.64388647  0.68816397 -2.79888244]
 [ 0.          0.          0.          1.        ]] [[ 0.69806346  0.32132623 -0.63988817 -5.07178551]
 [ 0.63314047 -0.69437718  0.34201386  6.76660804]
 [-0.33442572 -0.64388647 -0.68816397  9.11527181]
 [ 0.          0.          0.          1.        ]]
[[ 0.54261197 -0.41166854 -0.73218936 -3.50750015]
 [ 0.46705637  0.8723647  -0.14435436  2.66550306]
 [ 0.6981623  -0.2636453   0.66562794 -3.57134265]
 [ 0.          0.          

In [211]:
# Formulating least squares from dataset
lhs = []
rhs = []
for i in range(numsamples):
    lhs.append(
        np.hstack([np.kron(gtAs[i][:3, :3], np.eye(4)), np.kron(-np.eye(3), gtBs[i].T)])
    )
    rhs.append(
        np.kron(gtAs[i][:3, -1], [0, 0, 0, -1])
    )
    
lhs = np.vstack(lhs)
rhs = np.hstack(rhs)

In [212]:
solution, loss, iterations, eigenvalues = np.linalg.lstsq(lhs, rhs, rcond=None)

x = np.eye(4)
x[:3, :] = solution[:12].reshape(3, 4)
z = np.eye(4)
z[:3, :] = solution[12:].reshape(3, 4)

print("SOLUTION:")
print(x)
print(z)

print("GT:")
print(gtX)
print(gtZ)

SOLUTION:
[[ 1.00020519  0.00001716 -0.00019669  0.99660519]
 [ 0.00000039  0.9998454   0.00035782  2.00296221]
 [ 0.00069163 -0.00076495  1.00043855  2.99848758]
 [ 0.          0.          0.          1.        ]]
[[ 1.00053501 -0.00028577  0.00065079  2.99186155]
 [ 0.00040612 -0.99887778 -0.00045267  3.00411158]
 [ 0.00080244  0.00116703 -1.00107635 10.00563734]
 [ 0.          0.          0.          1.        ]]
GT:
[[1. 0. 0. 1.]
 [0. 1. 0. 2.]
 [0. 0. 1. 3.]
 [0. 0. 0. 1.]]
[[ 1. -0. -0.  3.]
 [ 0. -1. -0.  3.]
 [ 0. -0. -1. 10.]
 [ 0.  0.  0.  1.]]


In [213]:
display(np.linalg.det(x))
display(np.linalg.det(z))
